### ISSUE TITLE
Codepoints support

### ISSUE THREAD

**Issue by Exoth** [glaszig/compass-fontcustom#16]
Starting from version 1.3.0 Fontcustom reuses codepoints from manifest file between font updates. It means that if you generate a font through compass-fontcustom, add an icon and recompile the font, part of styles will be wrong, as they are generated alphabetically, which is not guaranteed now.

**Comment by cah4a** [comment]
Is anybody here still left alive?

**Comment by Exoth** [comment]
Sorry, but I haven't worked with this gem for long time already.

**Comment by glaszig** [comment]
implemented by #19, i hope.
