### ISSUE TITLE
Wrong font filename in compiled stylesheet

### ISSUE THREAD

**Issue by cah4a** [glaszig/compass-fontcustom#17]
Console output:

```
WARNING: 'icon-preview.eot?' was not found (or cannot be read) in project/web/theme/fonts
WARNING: 'icon-preview.woff' was not found (or cannot be read) in project/web/theme/fonts
WARNING: 'icon-preview.ttf' was not found (or cannot be read) in project/web/theme/fonts
WARNING: 'icon-preview.svg' was not found (or cannot be read) in project/web/theme/fonts
```

Generated stylesheet:

``` css
@font-face {
  font-family: "icon";
  src: url('../fonts/icon-preview.eot?#iefix') format('embedded-opentype'), url('../fonts/icon-preview.woff') format('woff'), url('../fonts/icon-preview.ttf') format('truetype'), url('../fonts/icon-preview.svg#icon') format('svg');
  font-weight: normal;
  font-style: normal;
}
```

System: MacOs

**Comment by cah4a** [comment]
Looks like `GlyphMap::filename` method can return wrong file such as `demo-font-preview.html` which causes font links in stylesheet are broken.

I see that bug is in the GlyphMap class at method
```ruby
def glob
    glob = File.join output_dir, "#{self.name}*.ttf"
    Dir[glob]
end
```

**Comment by vladislavs** [comment]
why it still not merged?

**Comment by cah4a** [comment]
Because nobody cares, i guess

You can use my fork if you want to. 
Just add this to Gemfile:
```
gem 'compass-fontcustom', :git => 'https://github.com/cah4a/compass-fontcustom.git', :branch => 'codepoints-support'
```

**Comment by vladislavs** [comment]
Seems, someone does care. 👍 Thank you both!

**Comment by cah4a** [comment]
Yeah! Cool)

**Comment by glaszig** [comment]
this library is not on my radar anymore. even less so since it has been abandoned (FontCustom/fontcustom#321). supposedly there's javascript-based build tools for the job. 

however, i've spent half the day trying to get travis to deploy a new version to rubygems. i did it for another gem but this time it doesn't work.

**Comment by glaszig** [comment]
alright. version 1.3.1 is out.
